### ISSUE TITLE
Posición del formulario de contacto

### ISSUE THREAD

**Issue by richin13** [richin13/info-rp#3]
La posición del formulario de contacto se ve cortada en la parte de nombre. Hay que darle un poco más de margen entre el top-nav y el contenedor del formulario

Probado en Mozilla Firefox 36

**Comment by Dascr32** [comment]
Si todavía falta terminar de acomodar bien, nada mas hice algo provisional. Porque si tenes razón esta medio desacomodado.

**Comment by richin13** [comment]
Con el estilo te agarrás vos! Jajaja (Y)

**Comment by richin13** [comment]
Arreglado!
